---
- hosts: all
  vars_files:
  - vars/external_vars.yaml
  - vars/nc_vars.yaml

  - name: Install NC apps
    become: true
    command: "{{ item }}"
    loop:
      - docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ app:install {{ list_apps }}
    register: install_nc-apps

#  - debug: msg="{{ install_nc-apps.stdout }}"