---
- hosts: all
  gather_facts: false
  vars_files:
  - ../vars/external_vars.yaml
  - ../vars/nc_vars.yaml
  - ../vars/nc-users_vars.yaml

  tasks:

  - name: Create the list of users to add
    set_fact:
      list_users_add: "{{ users_install.split(',') }}"
    ignore_errors: true

  - name: Create the list of users to remove
    set_fact:
      list_user_remove: "{{ users_remove.split(',') }}"
    ignore_errors: true


  - name: Create the list of users to enable
    set_fact:
      list_users_enable: "{{ users_enable.split(',') }}"
    ignore_errors: true


  - name: Create the list of users to disable
    set_fact:
      list_users_disable: "{{ users_disable.split(',') }}"
    ignore_errors: true

  - name: Add NC users, but not enable

    become: true
    command: docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ app:add --keep-disabled {{ item }}
    with_items: "{{ list_users_add }}"
#    when: (list_users_add is defined) and (list_users_add != None)
    ignore_errors: true
    register: add_nc_users

#  - debug: msg="{{ install_nc_apps.stdout }}"

  - name: Enable NC users
    become: true
    command: docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ user:delete {{ item }}
    with_items: "{{ list_users_enable }}"
#    when: (list_users_enable is defined) and (list_users_enable != None)
    ignore_errors: true
    register: enable_nc_users

#  - debug: msg="{{ enable_nc_apps.stdout }}"

  - name: Disable NC users
    become: true
    command: docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ user:disable {{ item }}
    with_items: "{{ list_users_disable }}"
#    when: (list_users_disable is defined) and (list_users_disable != None)
    ignore_errors: true
    register: disable_nc_users

#  - debug: msg="{{ disable_nc_apps.stdout }}"


  - name: Remove NC apps
    become: true
    command: docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ app:remove {{ item }}
    with_items: "{{ list_users_remove }}"
#    when: (list_users_remove is defined) and (list_users_remove != None)
    ignore_errors: true
    register: remove_nc_users


#  - debug: msg="{{ remove_nc_apps.stdout }}"
