---
- hosts: all
  gather_facts: false
  vars_files:
  - ../vars/external_vars.yaml
  - ../vars/nc_vars.yaml

  tasks:

  - name: Read users
    read_csv:
      path: ~/tf-nc/csv/users.csv
    register: users
    delegate_to: localhost

  - name: Add NC users
    become: true
    command: docker exec -u 33 nextcloud-app bash -c 'OC_PASS="{{ lookup('password','/dev/null length=10') }}" && export OC_PASS && {{ APP_PATH }}/occ user:add --password-from-env --group="{{ user.GID }}" --display-name="{{ user.DisplayName }}"  "{{ user.UID }}"'
    when: user.Deleted == "false"
    loop: "{{ users.list }}"
    loop_control:
      loop_var: user
    ignore_errors: true
    register: add_nc_users

  - name: Update user settings
    become: true
    shell: |
      docker exec -u 33 nextcloud-app {{ APP_PATH }}/occ user:setting {{ user.UID }} settings email {{ user.Email }}
      docker exec -u 33 nextcloud-app {{ APP_PATH }}/occ user:setting {{ user.UID }} files quota {{ user.Quota }}
    loop: "{{ users.list }}"
    loop_control:
      loop_var: user
#    ignore_errors: true
    register: updated_users


  - name: Enable users
    become: true
    command: docker exec -u 33 nextcloud-app {{ APP_PATH }}/occ user:enable {{ user.UID }}
    when: user.Enabled == "true"
    loop: "{{ users.list }}"
    loop_control:
      loop_var: user
#    ignore_errors: true
    register: enable_nc_users

  - name: Disable users
    become: true
    command: docker exec -u 33 nextcloud-app {{ APP_PATH }}/occ user:disable {{ user.UID }}
    when: user.Enabled == "false"
    loop: "{{ users.list }}"
    loop_control:
      loop_var: user
#    ignore_errors: true
    register: disable_nc_users


  - name: Delete users
    become: true
    command: docker exec -u 33 nextcloud-app {{ APP_PATH }}/occ user:delete {{ user.UID }}
    when: user.Deleted == "true"
    loop: "{{ users.list }}"
    loop_control:
      loop_var: user
#    ignore_errors: true
    register: delete_nc_users
