---
- hosts: docker_compose
  gather_facts: false
  vars_files:
  - ../vars/external_vars.yaml
  - ../vars/nc_vars.yaml

  tasks:

  - name: current directory
    command: pwd
    register: pwd_res
  - debug:
       var: pwd_res.stdout

  - name: Read apps
    read_csv:
      path: csv/apps.csv
    register: apps
    delegate_to: localhost

  - name: Add NC apps
    become: true
    command: docker exec -u 33 nextcloud-app {{ APP_PATH }}/occ app:install -f --keep-disabled "{{ app.AppName }}"
    when: app.Removed == "false"
    loop: "{{ apps.list }}"
    loop_control:
      loop_var: app
    ignore_errors: true
    register: add_nc_apps

  - name: Enable apps
    become: true
    command: docker exec -u 33 nextcloud-app {{ APP_PATH }}/occ app:enable -f {{ app.AppName }}
    when: app.Enabled == "true"
    loop: "{{ apps.list }}"
    loop_control:
      loop_var: app
    ignore_errors: true
    register: enable_nc_apps

  - name: Disable apps
    become: true
    command: docker exec -u 33 nextcloud-app {{ APP_PATH }}/occ app:disable {{ app.AppName }}
    when: app.Enabled == "false"
    loop: "{{ apps.list }}"
    loop_control:
      loop_var: app
    ignore_errors: true
    register: disable_nc_apps


  - name: Remove apps
    become: true
    command: docker exec -u 33 nextcloud-app {{ APP_PATH }}/occ app:remove {{ app.AppName }}
    when: app.Removed == "true"
    loop: "{{ apps.list }}"
    loop_control:
      loop_var: app
#    ignore_errors: true
    register: remove_nc_apps
