# Copy docker images to remote VM, create environment variables
---
- hosts: all
  become: true
  vars_files:
   - vars/external_vars.yaml

  tasks:

  - name: Create remote directory project
    file:
      path: "/opt/docker"
      state: directory

  - name: Copying docker-compose.yaml
    copy:
      src: ~/tf-nc/docker/docker-compose.yaml
      dest: /opt/docker

  - name: Copying credentials.env
    copy:
      src: ~/tf-nc/docker/credentials.env
      dest: /opt/docker

  - name: Copying virtual_host.env
    copy:
      src: ~/tf-nc/docker/virtual_host.env
      dest: /opt/docker

  - name: Append virtual_host.env with public dns host name
    shell:
      cmd: 'echo VIRTUAL_HOST=\"{{ virtual_host }}\" >> virtual_host.env'
      chdir: /opt/docker