# Copy docker images to remote VM
---
- hosts: all

  vars_files:
   - vars/external_vars.yaml

  tasks:

  - name: Create remote directory project
    file:
      path: "~/project"
      state: directory

  - name: Copying docker-compose.yaml
    copy:
      src: ~/epam-devops-learning/project/tf-nc/docker/docker-compose.yaml
      dest: ~/docker
