# Copy docker images to remote VM, create environment variables
---
- hosts: all

  vars_files:
   - vars/external_vars.yaml

  tasks:

  - name: Create remote directory project
    file:
      path: "~/docker"
      state: directory

  - name: Copying docker-compose.yaml
    copy:
      src: ~/tf-nc/docker/docker-compose.yaml
      dest: ~/docker

  - name: Create hosts.env
    shell:
      cmd: 'echo VIRTUAL_HOST=\"{{ virtual_host }}\" > virtual_host.env'
      chdir: ~/docker