---
- hosts: localhost
  connection: local
  vars_files:
  - vars/external_vars.yaml
  - vars/github_vars.yaml

  tasks:

  - name: Add a new deploy key to a GitHub repository, replace an existing key, use an OAuth2 token to authenticate
    community.general.github_deploy_key:
      owner: "ostasevych"
      repository: "tf-nc"
      name: "new-deploy-key"
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      force: yes
      token: "{{ token }}"

  - name: testing SSH connection with GitHib
    command: ssh -T -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null git@github.com
    ignore_errors: true

  - name:  create a new webhook that triggers on push (password auth)
    community.general.github_webhook:
      repository: "ostasevych/tf-nc"
      url: "http://{{ jenkins_host_ip }}:{{ jenkins_http_port }}/github-webhook/"
      events:
        - push
      user: "ostasevych"
      token: "{{ token }}"
