---
- hosts: localhost
  vars_files:
  - vars/external_vars.yaml

  tasks:

  - name: install community.general collection
    command: ansible-galaxy collection install community.general

  - name: Add a new deploy key to a GitHub repository, replace an existing key, use an OAuth2 token to authenticate
    community.general.github_deploy_key:
      owner: "ostasevych"
      repository: "tf-nc"
      name: "new-deploy-key"
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      force: yes
      token: "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"

  - name: testing SSH connection with GitHib
    command: ssh -T git@github.com
    ignore_errors: true
#    register: github_test

#  - debug:
#      var: github_test.stdout

  - name: install PyGithub
    command: pip3 install pygithub

  - name:  create a new webhook that triggers on push (password auth)
    community.general.github_webhook:
      repository: "ostasevych/tf-nc"
      url: "http://{{ jenkins_host_ip }}:{{ jenkins_http_port }}/github-webhook/"
      events:
        - push
      user: "ostasevych"
      token: "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"
