---
- hosts: all
  vars_files:
  - vars/credentials.yaml
  - vars/external_vars.yaml

#      docker exec -u 33 nextcloud-app sh -l -c "php {{ APP_PATH }}/occ maintenance:install --database {{ DB_TYPE }} --database-host {{ DB_HOST }} --database-name {{ DB_NAME }} --database-user {{ DB_USER }} --database-pass {{ DB_PASS }} --admin-user {{ ADMIN_USER }} --admin-pass {{ ADMIN_PASS }} --data-dir {{ APP_PATH }}/data"
#      docker exec -u 33 nextcloud-app sh -l -c "php {{ APP_PATH }}/occ config:system:set trusted_domains 2 --value={{ virtual_host }}"

  tasks:
  - name: first occ init
    become: true
    shell: docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ maintenance:install --database {{ DB_TYPE }} --database-host {{ DB_HOST }} --database-name {{ DB_NAME }} --database-user {{ DB_USER }} --database-pass {{ DB_PASS }} --admin-user {{ ADMIN_USER }} --admin-pass {{ ADMIN_PASS }} --data-dir {{ APP_PATH }}/data
    register: oc_init

  - debug: msg="{{ oc_init.stdout }}"

  - name: add trusted domain
    become: true
    shell: docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ config:system:set trusted_domains 2 --value={{ virtual_host }}
    register: trusted_add

  - debug: msg="{{ trusted_add.stdout }}"