---
- hosts: all
  vars_files:
  - vars/credentials.yaml
  - vars/external_vars.yaml
  - vars/app_vars.yaml

  tasks:
  - name: First occ init, create admin user
    become: true
    command: "{{ item }}"
    loop:
      - sleep 2m
      - docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ maintenance:install --database {{ DB_TYPE }} --database-host {{ DB_HOST }} --database-name {{ DB_NAME }} --database-user {{ DB_USER }} --database-pass {{ DB_PASS }} --admin-user {{ ADMIN_USER }} --admin-pass {{ ADMIN_PASS }} --data-dir {{ APP_PATH }}/data
    register: occ_init

#  - debug: msg="{{ occ_init.stdout }}"

  - name: Add current trusted domain
    become: true
    command: "{{ item }}"
    loop:
      - docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ config:system:set trusted_domains 2 --value={{ virtual_host }}
    register: trusted_add

#  - debug: msg="{{ trusted_add.stdout }}"