---
- hosts: all
  vars_files:
  - vars/credentials.yaml
  - vars/external_vars.yaml
  - vars/nc_vars.yaml

  tasks:
  - name: Install and initialise Nextcloud, create admin user
    become: true
    command: "{{ item }}"
    loop:
      - sleep 2m
      - docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ maintenance:install --database {{ DB_TYPE }} --database-host {{ DB_HOST }} --database-name {{ DB_NAME }} --database-user {{ DB_USER }} --database-pass {{ DB_PASS }} --admin-user {{ ADMIN_USER }} --admin-pass {{ ADMIN_PASS }} --data-dir {{ APP_PATH }}/data
    register: occ_init

#  - debug: msg="{{ occ_init.stdout }}"

  - name: Adding variables to config.php file
    become: true
    shell: |
      docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ config:system:set trusted_domains 1 --value={{ virtual_host_ip }}
      docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ config:system:set trusted_domains 2 --value={{ virtual_host }}
      docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ config:system:set filesystem_check_changes --value='0'
      docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ config:system:set overwrite.cli.url --value='https://{{ virtual_host }}'
      docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ config:system:set overwrite.protocol --value='https'
      docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ config:system:set default_phone_region --value='UA'
      docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ config:system:set loglevel --value=2
      docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ security:certificates:import /etc/nginx/certs/{{ virtual_host }}.crt
    register: set_config

#  - debug: msg="{{ set_config.stdout }}"

  - name: Hacking .htaccess to fix .well-known issue on self-signed host
    become: true
    command: sed -i 's+/remote.php/dav+https://%{SERVER_NAME}/remote.php/dav+g' /data/nextcloud/app/html/.htaccess
    register: set_well_known

  - name: Installing Community Document Server and OnlyOffice connector
    become: true
    shell: |
      curl -L -o /data/nextcloud/app/custom_apps/documentserver_community.tar.gz https://github.com/nextcloud/documentserver_community/releases/download/v0.1.10/documentserver_community.tar.gz
      tar -zxf /data/nextcloud/app/custom_apps/documentserver_community.tar.gz
      rm -f /data/nextcloud/app/custom_apps/documentserver_community.tar.gz
      docker exec -it -u 33 nextcloud-app chown www-data:www-data {{ APP_PATH }}/custom_apps
      docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ app:enable documentserver_community
      docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ app:install onlyoffice
    register: install_onlyoffice
     
#  - debug: msg="{{ install_onlyoffice.stdout }}"