---
- hosts: all
  vars_files:
  - vars/credentials.yaml
  - vars/external_vars.yaml
  - vars/nc_vars.yaml

  tasks:
  - name: Install and initialise Nextcloud, create admin user
    become: true
    command: "{{ item }}"
    loop:
      - sleep 2m
      - docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ maintenance:install --database {{ DB_TYPE }} --database-host {{ DB_HOST }} --database-name {{ DB_NAME }} --database-user {{ DB_USER }} --database-pass {{ DB_PASS }} --admin-user {{ ADMIN_USER }} --admin-pass {{ ADMIN_PASS }} --data-dir {{ APP_PATH }}/data
    register: occ_init

  - name: Adding variables to config.php file
    become: true
    command: docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ {{item}}
    with_items:
      - config:system:set trusted_domains 1 --value={{ virtual_host_ip }}
      - config:system:set trusted_domains 2 --value={{ virtual_host }}
      - config:system:set filesystem_check_changes --value='0'
      - config:system:set overwrite.cli.url --value='https://{{ virtual_host }}'
      - config:system:set overwriteprotocol --value='https'
      - config:system:set default_phone_region --value='UA'
      - config:system:set loglevel --value=2
      - security:certificates:import /etc/nginx/certs/{{ virtual_host }}.crt
    register: set_config

  - name: Hacking .htaccess to fix .well-known issue on self-signed host
    become: true
    command: sed -i 's+/remote.php/dav+https://%{SERVER_NAME}/remote.php/dav+g' /data/nextcloud/app/html/.htaccess
    register: set_well_known

  - name: Adding CA certificates
    become: true
    command: docker exec -it nextcloud-app bash -c "{{item}}"
    with_items:
      - cp -f /etc/nginx/certs/*.crt /usr/share/ca-certificates
      - echo 'ca.crt' >> /etc/ca-certificates.conf
      - echo '{{ virtual_host }}.crt' >> /etc/ca-certificates.conf
      - update-ca-certificates
    register: install_certs

