---
- hosts: all
  vars_files:
  - vars/external_vars.yaml
  - vars/nc_vars.yaml

  tasks:

  - name: Installing Community Document Server and OnlyOffice connector
    become: true
    shell: |
      curl -L -o /data/nextcloud/app/custom_apps/documentserver_community.tar.gz https://github.com/nextcloud/documentserver_community/releases/download/v0.1.10/documentserver_community.tar.gz
      cd /data/nextcloud/app/custom_apps
      tar -zxf documentserver_community.tar.gz
      rm -f documentserver_community.tar.gz
      chown -R www-data:www-data documentserver_community/*
      docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ app:enable documentserver_community
      docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ app:install onlyoffice
      docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ config:system:set allow_local_remote_servers --value=true
    register: install_onlyoffice
    ignore_errors: true

  - debug: msg="{{ install_onlyoffice.stdout }}"