---
- hosts: all
  vars_files:
  - vars/external_vars.yaml
  - vars/nc_vars.yaml

  tasks:

  - name: Download and untar Community Document Server
    become: true
    command: docker exec -it -u 33 nextcloud-app bash -c "{{item}}"
    with_items:
      - curl -L -o {{ APP_PATH }}/custom_apps/documentserver_community.tar.gz https://github.com/nextcloud/documentserver_community/releases/download/v0.1.10/documentserver_community.tar.gz
      - cd {{ APP_PATH }}/custom_apps && tar -zxvf documentserver_community.tar.gz
      - rm -f {{ APP_PATH }}/custom_apps/documentserver_community.tar.gz
    register: download_cds

  - name: Install and enable Community Document Server and OnlyOffice connector
    become: true
    command: docker exec -it -u 33 nextcloud-app {{ APP_PATH }}/occ {{item}}
    with_items:
      - app:enable documentserver_community
      - app:install onlyoffice
      - app:enable onlyoffice
      - config:system:set allow_local_remote_servers --value=true
      - config:app:set onlyoffice DocumentServerUrl --value https://{{ virtual_host }}/index.php/apps/documentserver_community/
    register: enable_cds_onlyoffice