---
- name: Install Oracle Java version 8
  hosts: localhost
  connection: local
  become: true
  
  tasks:
  - name: Install dependencies
    become: yes
    apt:
      name: "{{ packages }}"  
    vars:
      packages:    
      - software-properties-common
      - dirmngr
      state: latest 
  
  - name: Accept Java 8 License
    become: yes
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
 
  - name: update cache and ignore errors in case of problems
    become: yes
    apt: update_cache=yes
    ignore_errors: yes

  - name: Install required Ubuntu packages
    become: yes
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - openjdk-8-jdk
      - ca-certificates
      state: latest 

