# Running docker images via docker-compose
---
- hosts: all

#  vars_files:
#   - vars/external_vars.yaml

  tasks:

  - name: Run containers in docker-compose
    become: true
    shell:
      cmd: "docker-compose start"
      chdir: /opt/docker
