# Stop docker image via docker-compose
---
- hosts: all

#  vars_files:
#   - vars/external_vars.yaml

  tasks:

  - name: Stop containers in docker-compose
    become: true
    shell:
      cmd: "docker-compose -f docker-compose.yaml stop"
      chdir: /opt/docker
