# Running up docker images via docker-compose
---
- hosts: all

  vars_files:
   - vars/external_vars.yaml

  tasks:

  - name: Run containers in docker-compose
    become: true
    shell:
      cmd: "VIRTUAL_HOST={{ virtual_host }} docker-compose up -d"
      chdir: /opt/docker
