# Upgrade docker images via docker-compose
---
- hosts: all

  vars_files:
   - vars/external_vars.yaml

  tasks:

  - name: Upgrade containers in docker-compose
    become: true
    shell:
      cmd: |
        docker-compose pull
        VIRTUAL_HOST={{ virtual_host }} docker-compose up -d --remove-orphans
        docker image prune -f
      chdir: /opt/docker
